# Generated by Django 5.2.3 on 2025-06-22 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='Название статуса', max_length=124)),
                ('color', models.CharField(db_comment='Цвет', max_length=7, null=True)),
            ],
            options={
                'verbose_name': 'delivery status',
                'verbose_name_plural': 'delivery statuses',
                'db_table': 'delivery_statuses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PackagingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='Название типа упаковки', max_length=124)),
            ],
            options={
                'verbose_name': 'packaging type',
                'verbose_name_plural': 'packaging types',
                'db_table': 'packaging_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='Название услуги', max_length=124)),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'db_table': 'services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TransportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='Название модели', max_length=124)),
            ],
            options={
                'verbose_name': 'transport model',
                'verbose_name_plural': 'transport models',
                'db_table': 'transport_models',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_number', models.CharField(db_comment='Номер транспорта', max_length=64)),
                ('departure_time', models.DateTimeField(db_comment='Время отправления')),
                ('arrival_time', models.DateTimeField(db_comment='Время прибытия')),
                ('distance_km', models.FloatField(db_comment='Пройденное расстояние в км', null=True)),
                ('file', models.FileField(db_comment='Файл с информацией о доставке', null=True, upload_to='delivery_files/')),
                ('tech_condition', models.CharField(choices=[('ok', 'Исправно'), ('broken', 'Неисправно')], db_comment='Техническое состояние', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Время создания')),
                ('status', models.ForeignKey(db_comment='Статус доставки', on_delete=django.db.models.deletion.PROTECT, to='api.deliverystatus')),
                ('packaging_type', models.ForeignKey(db_comment='Тип упаковки', on_delete=django.db.models.deletion.PROTECT, to='api.packagingtype')),
                ('services', models.ManyToManyField(db_comment='Услуги', db_table='deliveries_services', to='api.service')),
                ('transport_model', models.ForeignKey(db_comment='Тип транспорта', on_delete=django.db.models.deletion.PROTECT, to='api.transportmodel')),
            ],
            options={
                'verbose_name': 'delivery',
                'verbose_name_plural': 'deliveries',
                'db_table': 'deliveries',
                'ordering': ['-created_at'],
            },
        ),
    ]
